//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPVVideoOverlay {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FPVVideoOverlay.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create video.
        /// </summary>
        internal static string CreateVideo {
            get {
                return ResourceManager.GetString("CreateVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop black sidebars (1920×1080 → 1080×1080).
        /// </summary>
        internal static string CropBlackBars {
            get {
                return ResourceManager.GetString("CropBlackBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the video duration..
        /// </summary>
        internal static string DurationError {
            get {
                return ResourceManager.GetString("DurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg stopped with an error..
        /// </summary>
        internal static string FFmpegError {
            get {
                return ResourceManager.GetString("FFmpegError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFprobe stopped with an error..
        /// </summary>
        internal static string FFprobeError {
            get {
                return ResourceManager.GetString("FFprobeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a valid main video!.
        /// </summary>
        internal static string InvalidMainVideo {
            get {
                return ResourceManager.GetString("InvalidMainVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an output location!.
        /// </summary>
        internal static string InvalidOutput {
            get {
                return ResourceManager.GetString("InvalidOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a valid overlay video!.
        /// </summary>
        internal static string InvalidOverlay {
            get {
                return ResourceManager.GetString("InvalidOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main video:.
        /// </summary>
        internal static string MainVideo {
            get {
                return ResourceManager.GetString("MainVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select main video.
        /// </summary>
        internal static string MainVideoDialogTitle {
            get {
                return ResourceManager.GetString("MainVideoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin:.
        /// </summary>
        internal static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save output video.
        /// </summary>
        internal static string OutputDialogTitle {
            get {
                return ResourceManager.GetString("OutputDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay:.
        /// </summary>
        internal static string Overlay {
            get {
                return ResourceManager.GetString("Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select overlay video.
        /// </summary>
        internal static string OverlayDialogTitle {
            get {
                return ResourceManager.GetString("OverlayDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay position:.
        /// </summary>
        internal static string OverlayPosition {
            get {
                return ResourceManager.GetString("OverlayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay size:.
        /// </summary>
        internal static string OverlaySize {
            get {
                return ResourceManager.GetString("OverlaySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom left.
        /// </summary>
        internal static string PositionBottomLeft {
            get {
                return ResourceManager.GetString("PositionBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom right.
        /// </summary>
        internal static string PositionBottomRight {
            get {
                return ResourceManager.GetString("PositionBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top left.
        /// </summary>
        internal static string PositionTopLeft {
            get {
                return ResourceManager.GetString("PositionTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top right.
        /// </summary>
        internal static string PositionTopRight {
            get {
                return ResourceManager.GetString("PositionTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Finished! 100%.
        /// </summary>
        internal static string StatusFinished {
            get {
                return ResourceManager.GetString("StatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Preparing....
        /// </summary>
        internal static string StatusPreparing {
            get {
                return ResourceManager.GetString("StatusPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Processing....
        /// </summary>
        internal static string StatusProcessing {
            get {
                return ResourceManager.GetString("StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Stopped.
        /// </summary>
        internal static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Stopping....
        /// </summary>
        internal static string StatusStopping {
            get {
                return ResourceManager.GetString("StatusStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to stop processing?.
        /// </summary>
        internal static string StopConfirmMessage {
            get {
                return ResourceManager.GetString("StopConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop processing.
        /// </summary>
        internal static string StopConfirmTitle {
            get {
                return ResourceManager.GetString("StopConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg could not be stopped..
        /// </summary>
        internal static string StopError {
            get {
                return ResourceManager.GetString("StopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏹ Stop processing.
        /// </summary>
        internal static string StopProcessing {
            get {
                return ResourceManager.GetString("StopProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video has been created!.
        /// </summary>
        internal static string VideoFinished {
            get {
                return ResourceManager.GetString("VideoFinished", resourceCulture);
            }
        }
    }
}
